version: "3.7"
services:
  webapp:
    build:
      context: .
    volumes:
      - ./app:/app
    env_file:
      - .env
    ports:
      - "${APP_PORT:-3000}:${APP_PORT:-3000}"
  database:
    image: mysql:5.7
    ports:
      - "3306"
    restart: always
    volumes:
      - mysql:/var/lib/mysql
      - ./container_config/mysql/migrations/:/docker-entrypoint-initdb.d:delegated
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpass'
      MYSQL_DATABASE: 'swoole_db'
      MYSQL_USER: 'dockeruser'
      MYSQL_PASSWORD: 'dockerpass'
      TZ: 'America/Sao_Paulo'

volumes:
  mysql:
    driver: local
